## Tips
- To avoid unpleasant surprises, I suggest you _run all cells in their order of appearance_ (__Cell__ $\rightarrow$ __Run All__).


- If the changes you've made to your solution don't seem to be showing up, try running __Kernel__ $\rightarrow$ __Restart & Run All__ from the menu.


- Before submitting your assignment, make sure everything runs as expected. First, restart the kernel (from the menu, select __Kernel__ $\rightarrow$ __Restart__) and then **run all cells** (from the menu, select __Cell__ $\rightarrow$ __Run All__).

## Reminder

- Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name, UA email, and collaborators below:



Several of the cells in this notebook are **read only** to ensure instructions aren't unintentionally altered.  

If you can't edit the cell, it is probably intentional.

In [1]:
NAME = "Wenmo Sun"
# University of Arizona email address
EMAIL = "wmsun@email.arizona.edu"
# Names of any collaborators.  Write N/A if none.
COLLABORATORS = "NA"

## Scratchpad

You are welcome to create new cells (see the __Cell__ menu) to experiment and debug your solution.

In [2]:
%load_ext autoreload
%autoreload 2

# Mini Python tutorial

This course uses Python 3.8.

Below is a very basic (and incomplete) overview of the Python language... 

For those completely new to Python, [this section of the official documentation may be useful](https://docs.python.org/3.8/library/stdtypes.html#common-sequence-operations).

In [3]:
# This is a comment.  
# Any line starting with # will be interpreted as a comment

# this is a string assigned to a variable
greeting = "hello"

# If enclosed in triple quotes, strings can also be multiline:

"""
I'm a multiline
string.
"""

# let's use a for loop to print it letter by letter
for letter in greeting:
    print(letter)
    
# Did you notice the indentation there?  Whitespace matters in Python!

# here's a list of integers

numbers = [1, 2, 3, 4]

# let's add one to each number using a list comprehension
# and assign the result to a variable called res
# list comprehensions are used widely in Python (they're very Pythonic!)

res = [num + 1 for num in numbers]

# let's confirm that it worked
print(res)

# now let's try spicing things up using a conditional to filter out all values greater than or equal to 3...
print([num for num in res if not num >= 3])

# Python 3.7 introduced "f-strings" as a convenient way of formatting strings using templates
# For example ...
name = "Josuke"

print(f"{greeting}, {name}!")

# f-strings are f-ing convenient!


# let's look at defining functions in Python..

def greet(name):
    print(f"Howdy, {name}!")

# here's how we call it...

greet("partner")

# let's add a description of the function...

def greet(name):
    """
    Prints a greeting given some name.
    
    :param name: the name to be addressed in the greeting
    :type name: str
    
    """
    print(f"Howdy, {name}!")
    
# I encourage you to use docstrings!

# Python introduced support for optional type hints in v3.5.
# You can read more aobut this feature here: https://docs.python.org/3.8/library/typing.html
# let's give it a try...
def add_six(num: int) -> int:
    return num + 6

# this should print 13
print(add_six(7))

# Python also has "anonymous functions" (also known as "lambda" functions)
# take a look at the following code:

greet_alt = lambda name: print(f"Hi, {name}!")

greet_alt("Fred")

# lambda functions are often passed to other functions
# For example, they can be used to specify how a sequence should be sorted
# let's sort a list of pairs by their second element
pairs = [("bounce", 32), ("bighorn", 12), ("radical", 4), ("analysis", 7)]
# -1 is last thing in some sequence, -2 is the second to last thing in some seq, etc.
print(sorted(pairs, key=lambda pair: pair[-1]))

# we can sort it by the first element instead
# NOTE: python indexing is zero-based
print(sorted(pairs, key=lambda pair: pair[0]))

# You can learn more about other core data types and their methods here: 
# https://docs.python.org/3.8/library/stdtypes.html

# Because of its extensive standard library, Python is often described as coming with "batteries included".  
# Take a look at these "batteries": https://docs.python.org/3.8/library/

# You now know enough to complete this homework assignment (or at least where to look)

h
e
l
l
o
[2, 3, 4, 5]
[2]
hello, Josuke!
Howdy, partner!
13
Hi, Fred!
[('radical', 4), ('analysis', 7), ('bighorn', 12), ('bounce', 32)]
[('analysis', 7), ('bighorn', 12), ('bounce', 32), ('radical', 4)]


In [4]:
from typing import Iterator, Iterable, List, Tuple, Text, Union
from sklearn.metrics import f1_score, accuracy_score
import numpy as np

from scipy.sparse import spmatrix

In [5]:
# Add needed imports here!
# YOUR CODE HERE
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression

#raise NotImplementedError()

In [6]:
# An NDArray can either be a numpy array (np.ndarray) or a sparse matrix (spmatrix)
NDArray = Union[np.ndarray, spmatrix]

np.random.seed(42)

# Assignment overview

In this assignment, you'll use a binomial logistic regression classifier with $n$-gram features to categorize SMS messages as **SPAM** or **NOT SPAM**.  

You will not be required to implement logistic regression from scratch.  Instead, you may use the `scikit-learn` implementation.  Be sure to carefully read the comments in the code skeleton provided.  To earn full credit, all tests must pass.

## `.read_smsspam()`

First we'll need data for training and evaluating our classifier.

Complete the function below which takes a path to a file (stored under `data` in the docker image) and returns a sequence of (label, text) pairs.

In [7]:
def read_smsspam(smsspam_path: Text) -> Iterator[Tuple[Text, Text]]:
    """
    Generates (label, text) tuples from the lines in an SMSSpam file.

    SMSSpam files contain one message per line. Each line is composed of a label
    (ham or spam), a tab character, and the text of the SMS. Here are some
    examples:

      spam	85233 FREE>Ringtone!Reply REAL
      ham	I can take you at like noon
      ham	Where is it. Is there any opening for mca.

    :param smsspam_path: The path of an SMSSpam file, formatted as above.
    :return: An iterator over (label, text) tuples.
    """
    # YOUR CODE HERE
#     res = []
#     with open(smsspam_path) as doc:
#         for line in doc:
#             temp = []
#             temp.append(line.strip().split("\t")[0])
#             temp.append(line.strip().split("\t")[1])
#             res.append(temp)
            
    with open(smsspam_path) as doc:
        lines = [line.strip().split("\t") for line in doc]
    return iter([(element[0], element[1]) for element in lines])
    
    # raise NotImplementedError()

## Test `.read_smsspam()` (3 pts)

In [8]:
# keep a counter here (instead of enumerate) in case the iterator is empty
count = 0
for example in read_smsspam("data/smsspam/SMSSpamCollection.train"):

    # make sure the right shape is returned
    assert len(example) == 2
    label, text = example

    # make sure the label is one of the expected two
    assert label in { "ham", "spam" }

    count += 1

# You should find exactly 3345 pairs in the training partition of the data
assert count == 3345

## `TextToFeatures`

Using the provided skeleton, complete the class `TextToFeatures` to transform text (documents) into real-valued features derived from the training data.

In [9]:
class TextToFeatures:
    def __init__(self):
        """
        Initializes an object for converting texts to features.    
        """
        
        # HINT: store a you may want to use a sklearn vectorizer.
        
        # YOUR CODE HERE
        self.vectorizer = TfidfVectorizer(ngram_range = (1, 2), token_pattern = r'\b\w+\b')
        
        #raise NotImplementedError()

    def fit(self, training_texts: Iterable[Text]) -> None:
        """
        Fits ("trains") a TextToFeature instance on a collection of documents.
        
        The provided training texts are analyzed to determine the vocabulary, 
        i.e., all feature values that the converter will support. 
        Each such feature value will be associated with a unique integer index 
        that may later be accessed via the .index() method.

        It is up to the implementer exactly what features to produce from a
        text, but the features will always include some single words and some
        multi-word expressions (e.g., "need" and "to you").
        
        
        docs = [
            "LOL. is this u? http://supersketchyurl.com/dangerous",
            "The IRS has been trying to reach you.",
            "Enclosed is your Coyote Joe's Marketplace Rewards Card."
            "Logan I'd like to add you to my professional network on LinkedIn",
        ]
        
        t2f = TextToFeatures()
        t2f.fit(docs)

        :param training_texts: The training texts.
        """
        # YOUR CODE HERE
        self.vectorizer.fit(training_texts)
        
        #raise NotImplementedError()
        
        
    def index(self, feature: Text) -> Union[None, int]:
        """
        Returns the index in the vocabulary of the given feature value.  
        If the features isn't present, return None.

        :param feature: A feature
        :return: The unique integer index associated with the feature or None if not present.
        """
        # YOUR CODE HERE
        # print(self.vectorizer.get_feature_names())
        if feature not in self.vectorizer.get_feature_names():
            return None
        else:
#             print("index: ", self.vectorizer.get_feature_names().index(feature))
            # print("feature names: ", self.vectorizer.get_feature_names())
#             print("number of features: ", len(self.vectorizer.get_feature_names()))
            return self.vectorizer.get_feature_names().index(feature)
        
        #raise NotImplementedError()

    def transform(self, texts: Iterable[Text]) -> NDArray:
        """
        Creates a feature matrix from a sequence of texts.
        
        docs = [
            "LOL. is this u? http://supersketchyurl.com/dangerous",
            "The IRS has been trying to reach you.",
            "Enclosed is your Coyote Joe's Marketplace Rewards Card."
            "I'd like to add you to my professional network on LinkedIn",
        ]
        
        t2f = TextToFeatures()
        t2f.fit(docs)

        # this produces a NDArray representing our features for the provided doc
        t2f.transform(["Let's meet at Coyote Joe's at 6."])


        Each row of the matrix corresponds to one of the input texts. The value
        at index j of row i is the value in the ith text of the feature
        associated with the unique integer j.

        It is up to the implementer what the value of a feature that is present
        in a text should be, though a common choice is 1. Features that are
        absent from a text will have the value 0.

        :param texts: A sequence of texts.
        :return: A matrix, with one row of feature values for each text.
        """
        # YOUR CODE HERE
#         print("to features array", self.vectorizer.transform(texts).toarray())
#         print("to features array type", type(self.vectorizer.transform(texts).toarray()))
#         print("columns of feature array: ", len(self.vectorizer.transform(texts).toarray()[0]))
        return self.vectorizer.transform(texts).toarray()
        
        # raise NotImplementedError()


## Test features (5 pts)

Let's test the behavior of your implementation of `TextToFeatures`...

In [10]:
training_texts: List[Text] = [
    "LOL. is this u? http://supersketchyurl.com/dangerous",
    "The IRS has been trying to reach you.",
    "You won't believe what in this doc.  Click here to find out!",
    "Enclosed is your Coyote Joe's Marketplace Rewards Card."
    "Logan I'd like to add you to my professional network on LinkedIn",
]
    
t2f = TextToFeatures()
t2f.fit(training_texts)

features = t2f.transform(["Is Bill in your professional network?"])
# ensure there is one row of features for each sentence
assert features.shape[0] == 1
# ensure there are nonzero values for some selected unigram and bigram features
assert t2f.index("reach") is not None

# if a feature wasn't observed during training, it should not have an index
assert t2f.index("strawberry kangaroos") is None
assert t2f.index("Jason Mendoza") is None

In [11]:
# get the texts from the training data
examples: Iterable[Tuple[str, str]]  = read_smsspam("data/smsspam/SMSSpamCollection.train")
training_texts: List[str]            = [text for _, text in examples]

# create the feature extractor from the training texts
t2f = TextToFeatures()
t2f.fit(training_texts)

# extract features for some made-up sentences
features = t2f.transform([
    "There are some things that I need to send to you.",
    "Hello!"
])

# make sure there is one row of features for each sentence
assert len(features.shape) == 2
n_rows, n_cols = features.shape
assert n_rows == 2

# make sure there are nonzero values for some selected unigram and bigram
# features in the first sentence
indices = [t2f.index(f) for f in ["need", "to you"]]
assert len(set(indices)) > 1
row_indices, col_indices = features[:, indices].nonzero()
assert np.all(row_indices == 0)
assert len(col_indices) == 2

## `TextToLabels`
Using the provided skeleton, complete the class `TextToLabels` to map class labels (strings) to integers.

In [12]:
class TextToLabels:
    def __init__(self):
        """
        Initializes an object for converting texts to labels.
        """
        # YOUR CODE HERE
        self.le = preprocessing.LabelEncoder()
        # raise NotImplementedError()

    def fit(self, training_labels: Iterable[Text]) -> None:
        """
        Assigns each distinct label a unique integer.
        
        
        Training labels are analyzed to determine the vocabulary, 
        i.e., all labels that the converter will support. 
        Each such label will be associated with a unique integer index 
        that may later be accessed via the .index() method.

        :param training_labels: The training labels.
        """
        # YOUR CODE HERE
        self.le.fit(training_labels)
        #raise NotImplementedError()
        
    def index(self, label: Text) -> Union[None, int]:
        """Returns the index in the vocabulary of the given label.

        :param label: A label
        :return: The unique integer index associated with the label.
        """
        # YOUR CODE HERE
        if label not in list(self.le.classes_):
            return None
        else:
            return list(self.le.classes_).index(label)
        #raise NotImplementedError()

    def transform(self, labels: Iterable[Text]) -> NDArray:
        """
        Creates a label vector from a sequence of labels.

        Each entry in the vector corresponds to one of the input labels. The
        value at index j is the unique integer associated with the jth label.

        :param labels: A sequence of labels.
        :return: A vector, with one entry for each label.
        """
        # YOUR CODE HERE
#         print("text to labels: ", self.le.transform(labels))
#         print("text to labels type: ", type(self.le.transform(labels)))
        return self.le.transform(labels)
        
        # raise NotImplementedError()
        
        
    def __contains__(self, label: Text) -> bool:
        """
        Special "dunder" method to check if a label is known to the TextToLabels instance.
        
        labeler = TextToLabels()
        labeler.fit(["POSITIVE", "NEGATIVE"])

        # should be True:
        "POSITIVE" in labeler 
        
        # should be False:
        "MBOP" in labeler
        
        :return: True if the label was seen in the training data; False otherwise
        """
        # NOTE: you do not need to change this if you've implemented .index() correctly!
        return False if self.index(label) is None else True

## Test labels (5pts)

In [13]:
training_labels = ["SPAM", "NOT_SPAM"]
lbl_encoder     = TextToLabels()
lbl_encoder.fit(training_labels)

assert "SPAM" in lbl_encoder
assert lbl_encoder.index("SPAM") is not None

# this label wasn't seen in the training data labels
assert "DISSERTATION" not in lbl_encoder
assert lbl_encoder.index("DISSERTATION") is None

In [14]:
def test_labels():
    # get the texts from the training data
    examples = read_smsspam("data/smsspam/SMSSpamCollection.train")
    labels = [label for label, _ in examples]

    # create the label encoder from the training texts
    lbl_encoder = TextToLabels()
    lbl_encoder.fit(labels)

    # just a simple convenience function to use for testing...
    to_labels = lambda labels: lbl_encoder.transform(labels)
    
    # make sure that some sample labels are encoded as expected
    ham_index = lbl_encoder.index("ham")
    spam_index = lbl_encoder.index("spam")
    assert ham_index != spam_index
    assert np.all(
        to_labels(["ham", "spam", "spam"]) == [ham_index, spam_index, spam_index]
    )

test_labels()

text to labels:  [0 1 1]
text to labels type:  <class 'numpy.ndarray'>


# `Classifier`
Using the provided skeleton, complete the class `Classifier` which will use `sklearn`'s logistic regression classifier.  You will implement the `train` and `predict` methods.

In [15]:
class Classifier:
    def __init__(self):
        """
        Initalizes a logistic regression classifier.
        """
        # YOUR CODE HERE
        self.clf = LogisticRegression(penalty='l2', C=1e2, class_weight='balanced', solver='liblinear')
        # raise NotImplementedError()

    def train(self, features: NDArray, labels: NDArray) -> None:
        """
        Trains the classifier using the given training examples.

        :param features: A feature matrix, where each row represents a text.
        Such matrices will typically be generated via TextToFeatures.
        :param labels: A label vector, where each entry represents a label.
        Such vectors will typically be generated via TextToLabels.
        """
        # YOUR CODE HERE
        self.clf.fit(features, labels)
        # raise NotImplementedError()
    
    # just an alias for "train"
    # fit = train
    
    def predict(self, features: NDArray) -> NDArray:
        """Makes predictions for each of the given examples.

        :param features: A feature matrix, where each row represents a text.
        Such matrices will typically be generated via TextToFeatures.
        :return: A prediction vector, where each entry represents a label.
        """
        # YOUR CODE HERE
#         print("features for prediction: ", features)
#         print("predicted features: ", self.clf.predict(features))
#         print("the type of predicted features: ", type(self.clf.predict(features)))
        # forgot to add return and it caused the NoneType issue in the test.
        return self.clf.predict(features)
        #raise NotImplementedError()

## Min F1 Score (4pts)

In [16]:
def test_prediction(min_f1=0.89, min_accuracy=0.97):
    # get texts and labels from the training data
    train_examples = read_smsspam("data/smsspam/SMSSpamCollection.train")
    train_labels, train_texts = zip(*train_examples)

    # get texts and labels from the development data
    dev_examples = read_smsspam("data/smsspam/SMSSpamCollection.devel")
    dev_labels, dev_texts = zip(*dev_examples)

    # fit/"train" the feature extractor and label encoder
    to_features = TextToFeatures()
    to_features.fit(train_texts)
    to_labels   = TextToLabels()
    to_labels.fit(train_labels)

    # train the classifier on the training data
    clf = Classifier()
    clf.train(to_features.transform(train_texts), to_labels.transform(train_labels))

    # make predictions on the development data
    predicted_indices = clf.predict(to_features.transform(dev_texts))
    assert np.array_equal(predicted_indices, predicted_indices.astype(bool))

    # measure performance of predictions
    dev_indices   = to_labels.transform(dev_labels)
    spam_label    = to_labels.index("spam")
    f1            = f1_score(dev_indices, predicted_indices, pos_label=spam_label)
    accuracy      = accuracy_score(dev_indices, predicted_indices)

    print(f"\n{f1:.1%} F1 and {accuracy:.1%} accuracy on SMSSpam development data")

    # make sure that performance is adequate
    assert f1 > min_f1
    assert accuracy > min_accuracy
    
test_prediction(min_f1=0.89, min_accuracy=0.97)

text to labels:  [0 0 1 ... 0 0 0]
text to labels type:  <class 'numpy.ndarray'>
features for prediction:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
predicted features:  [0 0 0 ... 0 0 0]
the type of predicted features:  <class 'numpy.ndarray'>
text to labels:  [0 0 0 ... 0 0 0]
text to labels type:  <class 'numpy.ndarray'>

95.0% F1 and 98.7% accuracy on SMSSpam development data


## High F1 score (2 pts)

Adjust your classifier (ex. features, regularization, etc.) as needed to achieve a minimum F1 score of 0.94.

In [17]:
test_prediction(min_f1=0.94, min_accuracy=0.98)

text to labels:  [0 0 1 ... 0 0 0]
text to labels type:  <class 'numpy.ndarray'>
features for prediction:  [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
predicted features:  [0 0 0 ... 0 0 0]
the type of predicted features:  <class 'numpy.ndarray'>
text to labels:  [0 0 0 ... 0 0 0]
text to labels type:  <class 'numpy.ndarray'>

95.0% F1 and 98.7% accuracy on SMSSpam development data
